week9/timetracking/config/routes.rb
Rails.application.routes.draw do
 get '/' => 'site#home'
 get '/contact' => 'site#contact'

 resources :projects, only: [:index,:show, :new, :create] do
 	resources :time_entries, except: [:show]
 end


 put '/project/:project_id/time_entries/:id/edit' => 'time_entries#edit'
 # get '/about' => 'site#about'

 # get '/projects' => 'projects#index'

 # get '/projects/new' => 'projects#new'

 # post '/projects' => 'projects#create'

 # get '/projects/:id' => 'projects#show'

 # get '/projects/:project_id/time_entries' => 'time_entries#index'

 # get '/projects/:project_id/time_entries' => 'time_entries#new'





end

week9/timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :time_entries

	validates :name, presence: true, uniqueness: true, length: {maximum: 30}, format: {with: /\A[a-zA-Z0-9]+/}
	
	def self.clean_old
		where("created_at < ?",  1.week.ago).destroy_all
	end

	def self.last_created_projects(limit)

		limit(limit).order(created_at: :desc)
	end

	def total_hours_in_month (month,year)
		date = Time.new(year, month)
		entries_in_month = time_entries.where(date: date.end_of_month)

		hours = entries_in_month.sum { |e| e.hours}
		minutes = entries_in_month.sum { |e| e.minutes}
		(minutes/60) + hours
	end
end

week9/timetracking/app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project
	validates :project, presence: true
	validates :hours, :minutes, presence: true, numericality: true
end

week9/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def new
		@project = Project.new

	end

	def create
	
		@project = Project.new(name: params[:project][:name],
			description: params[:project][:description])

		@project.save

		redirect_to '/projects'
	end

	def show
		
			@project = Project.find_by(id:params[:id])
			unless @project
				render 'no_project_found'
			end
			



	end
end

week9/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home #this is called an action
		render 'home'
	end
	def contact
		render 'contact'
	end
	def about
		render 'about'
	end
end

week9/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

	def destroy
		flash[:success] = 'Time Entry Deleted'
		@project = Project.find(params[:project_id])
    	@time_entry = @project.time_entries.find(params[:id])
    	 
    	 @time_entry.destroy
    		redirect_to project_time_entries_path(@project)
    
    			# render 'new'
 

	end

	def update
		@project = Project.find(params[:project_id])
		time_entry = @project.time_entries.find(params[:id])
		# time_entry_params = params.require(:time_entry).permit( :hours, :minutes, :date, :comment)
		
		
			if time_entry.update(time_entry_params)
				redirect_to project_time_entries_path(@project)
			else
				render 'edit'
			end

	end

	def edit

		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])

	end

	 def new

	 	@project = Project.find(params[:project_id])
	 	@time_entry = @project.time_entries.new
	 	@time
	 end

	def create
		# @input: params[:project_id] and params[:time_entry]
		@project = Project.find params[:project_id]
		# time_entry_params = params.require(:time_entry).permit(
		# 	:hours, :minutes, :date)
		
		@time_entry = @project.time_entries.new(time_entry_params)

			if @time_entry.save
				flash[:notice] = "Time Entry Created Successfully"
				redirect_to project_time_entries_path(@project), notice: "Time Entry Created Successfully"
			else
				render 'new'
			end

	end



	 def index
	 	@project = Project.find(params[:project_id])
	 	@time_entries = @project.time_entries
	 end




private

	def time_entry_params 
	params.require(:time_entry).permit( :hours, :minutes, :date, :comment)

	end
end

week9/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week9/timetracking/app/helpers/site_helper.rb
module SiteHelper
end

week9/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week9/timetracking/app/views/projects/index.html.erb
<ul>
	<% @projects.each do |project| %>
		<li>
			<%= link_to(project.name, project_time_entries_path(project)) %>
			<% if project.description.blank? %>
				<%= project.name %>
				<% else %>
				<%=project.name %> - <%=project.description %>
				<% end %>
		</li>
	<% end %>
</ul>

week9/timetracking/app/views/projects/new.html.erb
<%= form_for @project do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :description %>
<%= f.text_area :description %>
<br>

<%= f.submit 'Save' %>
<% end %>

week9/timetracking/app/views/projects/no_project_found.html.erb
No project found!

week9/timetracking/app/views/projects/show.html.erb
This project is called <%= @project.name %>

<h1><%= @project.name %></h1>
<p><% @project.description %></p>

week9/timetracking/app/views/site/about.html.erb
<h1>Hi my name is Ryan</h1>

week9/timetracking/app/views/site/contact.html.erb
<p>contact@example.com</p>

week9/timetracking/app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack Powered</p>

week9/timetracking/app/views/time_entries/_form.html.erb
<% if @time_entry.errors.any? %>
<ul>
	<% @time_entry.errors.full_messages.each do |error_msg| %>
	<li><%= error_msg %><li>
	<% end %>
<ul>
<% end %>




<%= form_for [@project, @time_entry] do |f| %>
	<%=f.label :hours %>
	<%= f.text_field :hours, size: 4 %>
	<br>
	<%=f.label :minutes %>
	<%= f.text_field :minutes, size: 4 %>
	<br>
	<%=f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%=f.label :comments %>
	<%= f.text_field :comments %>
	<br>

	<%= f.submit 'Save' %>
	<%= link_to 'Cancel', project_time_entries_path(@project) %>
	<% end %>

	

week9/timetracking/app/views/time_entries/edit.html.erb
<%= render partial: "form" %>




<!-- <ul>
	<% @time_entry.errors.full_messages.each do |error_msg| %>
	<li><%= error_msg %><li>
	<% end %>
<ul> -->
<!-- # <%= form_for [@project, @time_entry] do |f| %>
# 	<%=f.label :hours %>
# 	<%= f.text_field :hours, size: 4 %>
# 	<br>
# 	<%=f.label :minutes %>
# 	<%= f.text_field :minutes, size: 4 %>
# 	<br>
# 	<%=f.label :date %>
# 	<%= f.date_field :date %>
# 	<br>
# 	<%=f.label :comments %>
# 	<%= f.text_field :comments %>
# 	<br>

# 	<%= f.submit 'Save' %>
# 	<%= link_to 'Cancel', project_time_entries_path(@project) %>
# 	<% end %> -->

week9/timetracking/app/views/time_entries/index.html.erb
<%= link_to("Projects", projects_path) %>
<% link_to("New Time Entry", new_project_time_entry_path) %>

<% if flash[:notice] %>
	<%= flash[:notice] %>
	
	<% end %>
<h1><%= @project.name %></h1>
<ol>
	<% @time_entries.each do |time_entry| %>
	<li>

		Hours:
		<%=time_entry.hours %>
		Minutes:
		<%=time_entry.minutes %>
		<% link_to "Edit TIme Entry", edit_project_time_entry_path(@project, time_entry) %>
	</li>

	<%=link_to 'Delete', project_time_entry_path(@project, time_entry), method: :delete, data: {confirm: "Are you sure?"} %>



	
	<% end %>

</ol>
<%= link_to 'add entry', new_project_time_entry_path %>
		<%= link_to 'Projects', projects_path %>

week9/timetracking/app/views/time_entries/new.html.erb
<%= render partial: "form" %>

<%= link_to("Cancel", project_time_entries_path(@project)) %>