week10/Auction/config/routes.rb
Rails.application.routes.draw do

   resources :users, only: [:create, :new] do
      resources :products, only: [:index, :show, :create, :destroy]
  end
end

week10/Auction/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
end

week10/Auction/app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
end

week10/Auction/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@products = @user.products.all
	end

	def show
		@user = User.find(params[:user_id])
		@product = @user.products.find(params[:id])

	end

	def create
	end

	def destroy
	end

end

week10/Auction/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(
			name: params[:user][:name]
			)
		@user.save

		redirect_to user_products_path(@user)
	end


end

week10/Auction/app/helpers/products_helper.rb
module ProductsHelper
end

week10/Auction/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week10/Auction/app/views/products/index.html.erb
<ul>
	<% @products.each do |product| %>
	<li>
		<%= product.title %><br><%=link_to "Show",user_product_path(@user,product)%>
		
	</li>
	<% end %>
</ul>

week10/Auction/app/views/products/show.html.erb
<h4>Hello!</h4>

<%= @product.description %>

week10/Auction/app/views/users/new.html.erb
<%= form_for @user do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>


<%= f.submit 'Save' %>
<% end %>

week10/Auction/app/views/users/show.html.erb
<%= form_for @users do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.submit "USER SAVE" %>
    <br>
<% end %>
<%= link_to("ADD PRODUCT", user_products_path) %>